/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int integer = 9;
  /** RegularExpression Id. */
  int digit = 10;
  /** RegularExpression Id. */
  int null_value = 11;
  /** RegularExpression Id. */
  int letter = 12;
  /** RegularExpression Id. */
  int data_type = 13;
  /** RegularExpression Id. */
  int name = 14;
  /** RegularExpression Id. */
  int column_name = 15;
  /** RegularExpression Id. */
  int literal = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "<integer>",
    "<digit>",
    "\"NULL\"",
    "<letter>",
    "<data_type>",
    "<name>",
    "<column_name>",
    "<literal>",
    "\",\"",
    "\"VALUES\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"DROP\"",
    "\"TABLE\"",
    "\"CREATE\"",
  };

}
