/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int digit = 9;
  /** RegularExpression Id. */
  int letter = 10;
  /** RegularExpression Id. */
  int integer = 11;
  /** RegularExpression Id. */
  int table_name = 12;
  /** RegularExpression Id. */
  int attribute_name = 13;
  /** RegularExpression Id. */
  int column_name = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "<digit>",
    "<letter>",
    "<integer>",
    "<table_name>",
    "<attribute_name>",
    "<column_name>",
    "\"DROP\"",
    "\"TABLE\"",
  };

}
